# eager_execution 机器学习平台用于研究和实验，非图计算

In [11]:
import tensorflow as tf
tf.enable_eager_execution()
import numpy as np
from pprint import pprint

In [16]:
# 直接返回结果，不需要session.run()
tf.executing_eagerly()
x = [[4]]
m = tf.matmul(x,x)
print("hello{}".format(m))
b = tf.add(m,1)
print(b)
pprint(m*b)
a = np.multiply(m,b)
pprint(a)
pprint(b.numpy())

hello[[16]]
tf.Tensor([[17]], shape=(1, 1), dtype=int32)
<tf.Tensor: id=109, shape=(1, 1), dtype=int32, numpy=array([[272]], dtype=int32)>
array([[272]], dtype=int32)
array([[17]], dtype=int32)


In [28]:
# tfe
tfe = tf.contrib.eager
def fizzbuzz(max_num):
    counter = tf.constant(0)
    max_num = tf.convert_to_tensor(max_num)
    for num in range(1, max_num.numpy()+1):
        num = tf.constant(num)
        if int(num % 3) == 0 and int(num % 5) == 0:
            print('FizzBuzz')
        elif int(num % 3) == 0:
            print('Fizz')
        elif int(num % 5) == 0:
            print('Buzz')
        else:
            print(num.numpy())
        counter += 1

max_num = tf.convert_to_tensor(32)
print(max_num)

tf.Tensor(32, shape=(), dtype=int32)
